
# ---- ENDPOINTS ----

mech_dems_endpoint = "tcp://localhost:5000"
mech_sens_endpoint = "tcp://localhost:5001"
cam_endpoint = "tcp://localhost:5010"
tc_endpoint = "tcp://localhost:5020"
tm_endpoint = "tcp://*:5030"
sim_endpoint = "tcp://localhost:5100"